DELETE FROM ttipo_personal;
DELETE FROM tpersona;
DELETE FROM tperfil;
DELETE FROM tmodulo;
DELETE FROM tsub_modulo;
DELETE FROM tpregunta_seguridad;
DELETE FROM tpersonal;
DELETE FROM timagen_personal;
DELETE FROM tpregunta_seguridad_personal;
